spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalCors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9090

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
